annotations:
  artifacthub.io/category: storage
  artifacthub.io/changes: |-
    - kind: changed
      description: "BREAKING: Refactored service architecture to separate ClusterIP for Web UI and LoadBalancer for torrent ports"
    - kind: changed
      description: "BREAKING: Service values structure changed from flat to nested (service.web and service.torrent)"
    - kind: changed
      description: "BREAKING: Service resource names changed (transmission and transmission-torrent)"
    - kind: added
      description: Add HTTPRoute support for Gateway API with sectionName support
    - kind: added
      description: Add Cilium LB-IPAM annotation support for LoadBalancer service
    - kind: added
      description: Add comprehensive test suite with 64 tests covering all resources
  artifacthub.io/license: BSD-3-Clause
  artifacthub.io/links: |
    - name: Chart Repository
      url: https://github.com/lexfrei/charts/
    - name: Transmission
      url: https://transmissionbt.com/
  artifacthub.io/signKey: |
    fingerprint: keyless
    url: https://github.com/lexfrei/charts/.github/workflows/publish-oci.yaml@refs/heads/master
apiVersion: v2
name: transmission
description: Transmission BitTorrent client Helm chart for Kubernetes
type: application
version: "1.0.0"
# renovate: datasource=docker depName=linuxserver/transmission
appVersion: "4.0.6"
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/transmission-icon.png
home: https://github.com/lexfrei/charts/
keywords:
  - transmission
  - bittorrent
  - torrent
  - download
  - p2p
  - helm-chart
  - kubernetes
maintainers:
  - name: lexfrei
    email: f@lex.la
    url: https://github.com/lexfrei
sources:
  - https://github.com/lexfrei/charts/
  - https://github.com/transmission/transmission
  - https://github.com/linuxserver/docker-transmission
kubeVersion: '>=1.19.0-0'
