annotations:
  artifacthub.io/category: storage
  artifacthub.io/changes: |-
    - kind: added
      description: "Add extraVolumes and extraVolumeMounts for flexible volume configuration"
    - kind: added
      description: "Add extraPersistentVolumes for static PV provisioning"
    - kind: added
      description: "Add extraPersistentVolumeClaims for additional PVC creation"
    - kind: added
      description: "Add example for separate incomplete downloads directory"
  artifacthub.io/license: BSD-3-Clause
  artifacthub.io/links: |
    - name: Chart Repository
      url: https://github.com/lexfrei/charts/
    - name: Transmission
      url: https://transmissionbt.com/
  artifacthub.io/signKey: |
    fingerprint: keyless
    url: https://github.com/lexfrei/charts/.github/workflows/publish-oci.yaml@refs/heads/master
apiVersion: v2
name: transmission
description: Transmission BitTorrent client Helm chart for Kubernetes
type: application
version: "1.3.0"
# renovate: datasource=docker depName=linuxserver/transmission
appVersion: "4.0.6"
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/transmission-icon.png
home: https://github.com/lexfrei/charts/
keywords:
  - transmission
  - bittorrent
  - torrent
  - download
  - p2p
  - helm-chart
  - kubernetes
maintainers:
  - name: lexfrei
    email: f@lex.la
    url: https://github.com/lexfrei
sources:
  - https://github.com/lexfrei/charts/
  - https://github.com/transmission/transmission
  - https://github.com/linuxserver/docker-transmission
kubeVersion: '>=1.19.0-0'
