annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/changes: |-
    - kind: added
      description: "Add schema validation for annotations (must be string values)"
    - kind: added
      description: "Add unit test for default annotations"
  artifacthub.io/crds: |
    - kind: Plan
      version: v1
      name: plans.upgrade.cattle.io
      displayName: Upgrade Plan
      description: Declarative upgrade plan for Kubernetes nodes with automated rolling upgrades
  artifacthub.io/license: BSD-3-Clause
  artifacthub.io/links: |
    - name: Chart Repository
      url: https://github.com/lexfrei/charts/
    - name: System Upgrade Controller
      url: https://github.com/rancher/system-upgrade-controller/
  artifacthub.io/signKey: |
    fingerprint: keyless
    url: https://github.com/lexfrei/charts/.github/workflows/publish-oci.yaml@refs/heads/master
apiVersion: v2
name: system-upgrade-controller
description: Kubernetes-native upgrade controller for nodes using declarative Plans
type: application
version: "0.2.1"
# renovate: datasource=github-releases depName=rancher/system-upgrade-controller
appVersion: "v0.18.0"
icon: https://avatars.githubusercontent.com/u/9343010
home: https://github.com/lexfrei/charts/
keywords:
  - system-upgrade
  - upgrade
  - controller
  - node-upgrade
  - k3s
  - rancher
  - helm-chart
  - kubernetes
  - infrastructure
  - automation
maintainers:
  - name: lexfrei
    email: f@lex.la
    url: https://github.com/lexfrei
sources:
  - https://github.com/lexfrei/charts/
  - https://github.com/rancher/system-upgrade-controller/
kubeVersion: '>=1.16.0-0'
