apiVersion: v2
name: me-site
description: A Helm chart for the Me-Site application
type: application
version: 0.5.1
appVersion: 1.0.0
maintainers:
  - name: lexfrei
    email: f@lex.la
    url: https://github.com/lexfrei
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: "Add schema validation for annotations (must be string values)"
    - kind: added
      description: "Add unit test for default annotations"
kubeVersion: '>=1.19.0-0'
