annotations:
  artifacthub.io/category: networking
  # Valid kinds for changes: added, changed, deprecated, removed, fixed, security
  # See: https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/changes: |-
    - kind: changed
      description: Update cloudflare/cloudflared docker tag to v2026.1.2
  artifacthub.io/license: BSD-3-Clause
  artifacthub.io/links: |
    - name: Chart Repository
      url: https://github.com/lexfrei/charts/
    - name: Cloudflare Cloudflared
      url: https://github.com/cloudflare/cloudflared/
  artifacthub.io/signKey: |
    fingerprint: keyless
    url: https://github.com/lexfrei/charts/.github/workflows/publish-oci.yaml@refs/heads/master
apiVersion: v2
name: cloudflare-tunnel
description: Creation of a cloudflared deployment - a reverse tunnel for an environment
type: application
version: "0.15.1"
kubeVersion: ">=1.21.0-0"
# renovate: datasource=docker depName=cloudflare/cloudflared
appVersion: "2026.1.2"
icon: https://avatars.githubusercontent.com/u/314135
home: https://github.com/lexfrei/charts/
keywords:
  - cloudflare
  - cloudflared
  - reverse-tunnel
  - tunnel
  - helm-chart
  - kubernetes
  - devops
  - networking
  - zero-trust
  - proxy
  - vpn
maintainers:
  - name: lexfrei
    email: f@lex.la
    url: https://github.com/lexfrei
sources:
  - https://github.com/lexfrei/charts/
  - https://github.com/cloudflare/cloudflared/
