{{- if .Values.controlPlane.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eclipse-edc.controlplane.fullname" . }}
  labels:
    {{- include "eclipse-edc.controlplane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controlPlane.replicaCount }}
  selector:
    matchLabels:
      {{- include "eclipse-edc.controlplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/controlplane/configmap.yaml") . | sha256sum }}
        {{- with .Values.controlPlane.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "eclipse-edc.controlplane.labels" . | nindent 8 }}
        {{- with .Values.controlPlane.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eclipse-edc.controlplane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: controlplane
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "eclipse-edc.controlplane.image" . }}
          imagePullPolicy: {{ .Values.controlPlane.image.pullPolicy }}
          ports:
            - name: management
              containerPort: {{ .Values.controlPlane.ports.management }}
              protocol: TCP
            - name: protocol
              containerPort: {{ .Values.controlPlane.ports.protocol }}
              protocol: TCP
            - name: default
              containerPort: {{ .Values.controlPlane.ports.default }}
              protocol: TCP
          env:
            - name: EDC_FS_CONFIG
              value: /app/config/edc.properties
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
            - name: tmp
              mountPath: /tmp
          {{- with .Values.controlPlane.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "eclipse-edc.controlplane.fullname" . }}
        - name: tmp
          emptyDir: {}
      {{- with .Values.controlPlane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlPlane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlPlane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
