{{- if and .Values.controlPlane.enabled .Values.controlPlane.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eclipse-edc.controlplane.serviceAccountName" . }}
  labels:
    {{- include "eclipse-edc.controlplane.labels" . | nindent 4 }}
  {{- with .Values.controlPlane.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
