{{- if .Values.controlPlane.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eclipse-edc.controlplane.fullname" . }}
  labels:
    {{- include "eclipse-edc.controlplane.labels" . | nindent 4 }}
  {{- with .Values.controlPlane.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controlPlane.service.type }}
  ports:
    - port: {{ .Values.controlPlane.ports.management }}
      targetPort: management
      protocol: TCP
      name: management
    - port: {{ .Values.controlPlane.ports.protocol }}
      targetPort: protocol
      protocol: TCP
      name: protocol
    - port: {{ .Values.controlPlane.ports.default }}
      targetPort: default
      protocol: TCP
      name: default
  selector:
    {{- include "eclipse-edc.controlplane.selectorLabels" . | nindent 4 }}
{{- end }}
