{{- if .Values.dataPlane.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eclipse-edc.dataplane.fullname" . }}
  labels:
    {{- include "eclipse-edc.dataplane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dataPlane.replicaCount }}
  selector:
    matchLabels:
      {{- include "eclipse-edc.dataplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/dataplane/configmap.yaml") . | sha256sum }}
        {{- with .Values.dataPlane.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "eclipse-edc.dataplane.labels" . | nindent 8 }}
        {{- with .Values.dataPlane.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eclipse-edc.dataplane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: dataplane
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "eclipse-edc.dataplane.image" . }}
          imagePullPolicy: {{ .Values.dataPlane.image.pullPolicy }}
          ports:
            - name: public
              containerPort: {{ .Values.dataPlane.ports.public }}
              protocol: TCP
            - name: control
              containerPort: {{ .Values.dataPlane.ports.control }}
              protocol: TCP
          env:
            - name: EDC_FS_CONFIG
              value: /app/config/edc.properties
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
            - name: tmp
              mountPath: /tmp
          {{- with .Values.dataPlane.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "eclipse-edc.dataplane.fullname" . }}
        - name: tmp
          emptyDir: {}
      {{- with .Values.dataPlane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataPlane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataPlane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
