{{- if and .Values.dataPlane.enabled .Values.dataPlane.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eclipse-edc.dataplane.serviceAccountName" . }}
  labels:
    {{- include "eclipse-edc.dataplane.labels" . | nindent 4 }}
  {{- with .Values.dataPlane.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
