{{- if .Values.dataPlane.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eclipse-edc.dataplane.fullname" . }}
  labels:
    {{- include "eclipse-edc.dataplane.labels" . | nindent 4 }}
  {{- with .Values.dataPlane.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.dataPlane.service.type }}
  ports:
    - port: {{ .Values.dataPlane.ports.public }}
      targetPort: public
      protocol: TCP
      name: public
    - port: {{ .Values.dataPlane.ports.control }}
      targetPort: control
      protocol: TCP
      name: control
  selector:
    {{- include "eclipse-edc.dataplane.selectorLabels" . | nindent 4 }}
{{- end }}
