{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "transmission.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow Web UI access
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.web.port }}
    # Allow torrent TCP connections
    - ports:
        - protocol: TCP
          port: {{ .Values.service.torrent.tcpPort }}
    # Allow torrent UDP connections
    - ports:
        - protocol: UDP
          port: {{ .Values.service.torrent.udpPort }}
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow torrent traffic (tracker, peers)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
