{{- if and (eq .Values.cloudflare.mode "remote") .Values.cloudflare.tunnelToken (not .Values.cloudflare.tunnelTokenSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}-token
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.cloudflare.tunnelToken | quote }}
{{- end }}
