apiVersion: v1
kind: Service
metadata:
  name: {{ include "eclipse-edc.fullname" . }}
  labels:
    {{- include "eclipse-edc.labels" . | nindent 4 }}
  {{- with .Values.connector.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.connector.service.type }}
  ports:
    - port: {{ .Values.connector.ports.default }}
      targetPort: default
      protocol: TCP
      name: default
    - port: {{ .Values.connector.ports.management }}
      targetPort: management
      protocol: TCP
      name: management
    - port: {{ .Values.connector.ports.protocol }}
      targetPort: protocol
      protocol: TCP
      name: protocol
    - port: {{ .Values.connector.ports.public }}
      targetPort: public
      protocol: TCP
      name: public
    - port: {{ .Values.connector.ports.control }}
      targetPort: control
      protocol: TCP
      name: control
  selector:
    {{- include "eclipse-edc.selectorLabels" . | nindent 4 }}
