{{- if .Values.connector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eclipse-edc.serviceAccountName" . }}
  labels:
    {{- include "eclipse-edc.labels" . | nindent 4 }}
  {{- with .Values.connector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
