{{- if .Values.enableDiscovery }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "extractedprism.fullname" . }}
  labels:
    {{- include "extractedprism.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "extractedprism.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "extractedprism.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
